# Generated by Django 5.1.2 on 2025-03-02 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0002_remove_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
