# Generated by Django 5.1.2 on 2024-11-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0003_alter_person_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="phone_number",
            field=models.CharField(max_length=10),
        ),
    ]
