# Generated by Django 5.1.2 on 2025-03-02 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Rendevouz", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment_booking",
            old_name="time",
            new_name="start_time",
        ),
        migrations.RemoveField(
            model_name="appointment_booking",
            name="task",
        ),
        migrations.AddField(
            model_name="appointment_booking",
            name="dogs",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment",
                to="Rendevouz.dog",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment_booking",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="appointment_booking",
            name="notes",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="appointment_booking",
            name="type",
            field=models.CharField(
                choices=[
                    ("PW", "pet walking"),
                    ("PS", "pet sitting"),
                    ("PT", "pet taxi"),
                ],
                default=1,
                max_length=2,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appointment_booking",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dog",
            name="dog_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="dog",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dogs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
