# Generated by Django 5.0 on 2025-03-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Rendevouz", "0002_rename_time_appointment_booking_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment_booking",
            name="dogs",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="appointment_booking",
            name="type",
            field=models.CharField(
                choices=[
                    ("DG", "Dog Walking"),
                    ("PM", "Pet Sitting My Home"),
                    ("PY", "Pet Sitting Your Home"),
                    ("PT", "Pet Taxi"),
                    ("AL", "Other"),
                ],
                max_length=2,
            ),
        ),
        migrations.DeleteModel(
            name="Dog",
        ),
    ]
