# Generated by Django 5.1.2 on 2025-03-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendevouz', '0002_rename_time_appointment_booking_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_booking',
            name='dogs',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
