# Generated by Django 5.1.2 on 2025-03-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendevouz', '0003_alter_appointment_booking_dogs_delete_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_booking',
            name='type',
            field=models.CharField(choices=[('DG', 'Dog Walking'), ('PM', 'Pet Sitting My Home'), ('PY', 'Pet Sitting Your Home'), ('PT', 'Pet Taxi'), ('AL', 'Other')], max_length=2),
        ),
    ]
