# Generated by Django 5.1.2 on 2025-03-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendevouz', '0004_alter_appointment_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_booking',
            name='end_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment_booking',
            name='start_time',
            field=models.DateField(),
        ),
    ]
