# Generated by Django 5.1.2 on 2025-03-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendevouz', '0005_alter_appointment_booking_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_booking',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment_booking',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
